name: After container image is pushed to Dockerhub

on:
  workflow_run:
    workflows: ["Build container image and push to Dockerhub"]
    types: [ "completed" ]

jobs:
  do_thing:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      TF_VAR_DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      TF_VAR_DOCKERHUB_IMAGE_NAME: ${{ vars.DOCKERHUB_IMAGE_NAME }}
      # TF_CONF_DIR: "./zedcloud_deployment_examples/edge_app_and_project_with_app_policy/"
      # TF_CONF_DIR: "./zedcloud_deployment_examples/edge_app_and_project_with_inst_replace/"
      TF_CONF_DIR: ${{ vars.TF_CONF_DIR }}
      TF_STATE_ZERO: ${{ vars.TF_STATE_ZERO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dockerhub_latest_tag which contains the tag of the container image that was just built
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          name: dockerhub_image_latest_tag
          path: dockerhub_image_latest_tag
          run_id: ${{ github.event.workflow_run.id }}

      - id: dockerhub_image_latest_tag
        name: Retrieve the tag of the container image
        run: echo "DOCKERHUB_IMAGE_LATEST_TAG=$(cat dockerhub_image_latest_tag/dockerhub_image_latest_tag)" >> $GITHUB_OUTPUT

        # TODO: This is needed only temporary, remove once a new release of
        # the provider is available from `zededa/terraform-provider/zedcloud`.
        # See also the comment in the terraform configuration file (something
        # like `terraform.tf` or `providers.tf`.
      - name: Download a pre-release version of the zedcloud terraform provider
        uses: robinraju/release-downloader@v1
        with:
          repository: 'andrei-zededa/terraform-provider-zedcloud'
          latest: true
          preRelease: true
          tag: 'v0.0.0-dev.fiximageupdate.1'
          fileName: 'terraform-provider-zedcloud*.tar.gz'
          tarBall: true
          out-file-path: './.terraform_plugins/'
          extract: true

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download any previous terraform state
        uses: badgerhobbs/terraform-state@v2
        # Case-insensitive match for vars.TF_STATE_ZERO != "yes"/"true".
        if: >-
         !contains(fromJSON('["yes", "true", "y"]'), format('{0}', vars.TF_STATE_ZERO).toLowerCase()) &&
         vars.TF_STATE_ZERO != true
        with:
          operation: download
          location: artifact
          github_token: ${{ secrets.GH_TOKEN }}
          encryption_key: ${{ secrets.TF_STATE_ENCRYPTION_KEY }}
          directory: ${{ vars.TF_CONF_DIR }}
        continue-on-error: true

      - id: tf_init
        run: terraform -chdir="${TF_CONF_DIR}" init -upgrade -plugin-dir=../../.terraform_plugins/

      - id: tf_plan
        run: terraform -chdir="${TF_CONF_DIR}" plan -no-color -out="./${TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG}.1st.tfplan" -exclude=zedcloud_network_instance.NET_INSTANCES -exclude=zedcloud_application_instance.APP_INSTANCES
        env:
          TF_VAR_ZEDEDA_CLOUD_URL: ${{ secrets.ZEDEDA_CLOUD_URL }}
          TF_VAR_ZEDEDA_CLOUD_TOKEN: ${{ secrets.ZEDEDA_CLOUD_TOKEN }}
          TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG: ${{ steps.dockerhub_image_latest_tag.outputs.DOCKERHUB_IMAGE_LATEST_TAG }}

      - id: tf_apply
        run: terraform -chdir="${TF_CONF_DIR}" apply -no-color -auto-approve "./${TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG}.1st.tfplan"
        env:
          TF_VAR_ZEDEDA_CLOUD_URL: ${{ secrets.ZEDEDA_CLOUD_URL }}
          TF_VAR_ZEDEDA_CLOUD_TOKEN: ${{ secrets.ZEDEDA_CLOUD_TOKEN }}
          TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG: ${{ steps.dockerhub_image_latest_tag.outputs.DOCKERHUB_IMAGE_LATEST_TAG }}

      - id: tf_plan
        run: terraform -chdir="${TF_CONF_DIR}" plan -no-color -out="./${TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG}.2nd.tfplan"
        env:
          TF_VAR_ZEDEDA_CLOUD_URL: ${{ secrets.ZEDEDA_CLOUD_URL }}
          TF_VAR_ZEDEDA_CLOUD_TOKEN: ${{ secrets.ZEDEDA_CLOUD_TOKEN }}
          TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG: ${{ steps.dockerhub_image_latest_tag.outputs.DOCKERHUB_IMAGE_LATEST_TAG }}

      - id: tf_apply
        run: terraform -chdir="${TF_CONF_DIR}" apply -no-color -auto-approve "./${TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG}.2nd.tfplan"
        env:
          TF_VAR_ZEDEDA_CLOUD_URL: ${{ secrets.ZEDEDA_CLOUD_URL }}
          TF_VAR_ZEDEDA_CLOUD_TOKEN: ${{ secrets.ZEDEDA_CLOUD_TOKEN }}
          TF_VAR_DOCKERHUB_IMAGE_LATEST_TAG: ${{ steps.dockerhub_image_latest_tag.outputs.DOCKERHUB_IMAGE_LATEST_TAG }}

      - name: Upload terraform state
        uses: badgerhobbs/terraform-state@v2
        with:
          operation: upload
          location: artifact
          github_token: ${{ secrets.GH_TOKEN }}
          encryption_key: ${{ secrets.TF_STATE_ENCRYPTION_KEY }}
          directory: ${{ vars.TF_CONF_DIR }}
