name: After container image is pushed to Dockerhub

on:
  workflow_run:
    workflows: ["Build container image and push to Dockerhub"]
    types: [ "completed" ]

jobs:
  do_thing:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download dockerhub_latest_tag
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          name: dockerhub_image_latest_tag
          path: dockerhub_image_latest_tag
          run_id: ${{ github.event.workflow_run.id }}

      - name: Debug 1
        run: cat dockerhub_image_latest_tag/dockerhub_image_latest_tag

        # TODO: This is needed only temporary, remove once a new release of
        # the provider is available from `zededa/terraform-provider/zedcloud`.
      - name: Download a pre-release version of the zedcloud terraform provider
        uses: robinraju/release-downloader@v1
        with:
          repository: 'andrei-zededa/terraform-provider-zedcloud'
          latest: true
          preRelease: true
          tag: 'v0.0.0-dev.fiximageupdate.1'
          fileName: 'terraform-provider*.tar.gz'
          tarBall: true
          out-file-path: './terraform_plugins/'
          extract: true

      - name: Debug 2
        run: ls -Rlsah ./terraform_plugins/

      - name: Debug 3
        run: echo "${{ toJSON(github.event) }}"

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - id: init
        run: |
          pwd
          ls -lsah
          terraform init --upgrade -plugin-dir=./terraform_plugins/ -chdir=./zedcloud_deployment/

      - id: plan
        run: |
          pwd
          ls -lsah
          terraform plan -no-color -chdir=./zedcloud_deployment/
      
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
