name: Build container image and push to Dockerhub

on:
  workflow_run:
    workflows: ["Go lint and build"]
    types:
      - completed
  push:
    tags: [ 'v*' ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.event_name != 'pull_request'
              && format('andreizededa/hello-zedcloud:latest,andreizededa/hello-zedcloud:{0}', github.ref_name)
              || ''
            }}
