name: Go lint and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1

    - name: Set up shellcheck
      uses: pollenjp/setup-shellcheck@v1.0.2

    - name: Lint
      run: make lint

    - name: Build
      run: make build
